package cli

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// Completion scripts are generated from CommandTree rather than written by
// hand, so they cannot drift from the commands they describe.
//
// Distribution names are resolved when the user presses Tab, by asking the
// binary, rather than baked into the script: a script generated last month must
// still know about a distribution installed this morning.

// completionPath is the sequence of words leading to a command, e.g.
// "disk config set".
type completionEntry struct {
	Path  string
	Desc  string
	Subs  []string
	Flags []string
	Args  []argKind
}

// flattenTree walks the tree into one entry per command path.
func flattenTree(nodes []cmdNode, prefix string) []completionEntry {
	var out []completionEntry
	for _, n := range nodes {
		path := n.Name
		if prefix != "" {
			path = prefix + " " + n.Name
		}
		e := completionEntry{Path: path, Desc: n.Desc, Flags: n.Flags, Args: n.Positional}
		for _, s := range n.Subs {
			e.Subs = append(e.Subs, s.Name)
		}
		out = append(out, e)
		out = append(out, flattenTree(n.Subs, path)...)
	}
	return out
}

// completionEntries returns the whole tree, sorted by path so the generated
// script is stable between runs.
func completionEntries() []completionEntry {
	out := flattenTree(CommandTree(), "")
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out
}

// words joins the completions offered for one command: its subcommands, then
// its flags, then the global flags.
func (e completionEntry) words() string {
	all := append([]string{}, e.Subs...)
	all = append(all, e.Flags...)
	all = append(all, globalFlags...)
	return strings.Join(dedupe(all), " ")
}

func dedupe(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if s == "" || seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}

// firstArg is the kind of the first positional slot, which is the one
// completion can usefully offer something for.
func (e completionEntry) firstArg() argKind {
	if len(e.Args) == 0 {
		return argNone
	}
	return e.Args[0]
}

// WriteCompletion writes the completion script for one shell.
func WriteCompletion(w io.Writer, shell string) error {
	switch shell {
	case "powershell":
		writePowerShellCompletion(w)
	case "bash":
		writeBashCompletion(w)
	case "zsh":
		writeZshCompletion(w)
	default:
		return fmt.Errorf("there is no completion for %q; the shells are: %s", shell, strings.Join(Shells, ", "))
	}
	return nil
}

func writePowerShellCompletion(w io.Writer) {
	fmt.Fprint(w, `# wslkit completion for PowerShell.
# Generated by: wslkit completion powershell
# Install with: wslkit completion powershell | Out-String | Invoke-Expression

$script:WslkitCommands = @{
`)
	for _, e := range completionEntries() {
		fmt.Fprintf(w, "  '%s' = '%s'\n", e.Path, e.words())
	}
	fmt.Fprint(w, `}

function script:WslkitDistros {
  # Asked at completion time, so a distribution installed since this script was
  # generated still completes.
  try { (wslkit disk list --json 2>$null) | ForEach-Object { ($_ | ConvertFrom-Json).name } } catch { @() }
}

Register-ArgumentCompleter -Native -CommandName wslkit -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)

  $words = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() })
  if ($wordToComplete) { $words = $words[0..($words.Count - 2)] }

  # Longest matching command path wins.
  $path = ''
  foreach ($word in $words) {
    if ($word.StartsWith('-')) { continue }
    $candidate = if ($path) { "$path $word" } else { $word }
    if ($script:WslkitCommands.ContainsKey($candidate)) { $path = $candidate } else { break }
  }

  $offered = if ($path) { $script:WslkitCommands[$path] } else { '`)
	fmt.Fprint(w, strings.Join(topLevelNames(), " "))
	fmt.Fprint(w, `' }
  $candidates = $offered -split ' '

  if ($script:WslkitDistroPaths -contains $path) { $candidates += script:WslkitDistros }

  $candidates | Where-Object { $_ -like "$wordToComplete*" } | Sort-Object -Unique | ForEach-Object {
    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
  }
}

$script:WslkitDistroPaths = @(`)
	fmt.Fprint(w, "'"+strings.Join(pathsTakingKind(argDistro), "', '")+"'")
	fmt.Fprint(w, ")\n")
}

func writeBashCompletion(w io.Writer) {
	fmt.Fprint(w, `# wslkit completion for bash.
# Generated by: wslkit completion bash
# Install with: source <(wslkit completion bash)

_wslkit_distros() {
  # Asked at completion time, so a distribution installed since this script was
  # generated still completes.
  wslkit disk list --json 2>/dev/null |
    sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p'
}

_wslkit() {
  local cur prev words cword path candidate offered
  cur="${COMP_WORDS[COMP_CWORD]}"
  path=""
  local i
  for (( i=1; i < COMP_CWORD; i++ )); do
    case "${COMP_WORDS[i]}" in
      -*) continue ;;
    esac
    if [ -z "$path" ]; then candidate="${COMP_WORDS[i]}"; else candidate="$path ${COMP_WORDS[i]}"; fi
    case "$candidate" in
`)
	for _, e := range completionEntries() {
		fmt.Fprintf(w, "      %s) path=\"%s\" ;;\n", quoteBashCase(e.Path), e.Path)
	}
	fmt.Fprint(w, `      *) break ;;
    esac
  done

  case "$path" in
`)
	for _, e := range completionEntries() {
		fmt.Fprintf(w, "    %s) offered=%q ;;\n", quoteBashCase(e.Path), e.words())
	}
	fmt.Fprintf(w, "    *) offered=%q ;;\n", strings.Join(topLevelNames(), " ")+" "+strings.Join(globalFlags, " "))
	fmt.Fprint(w, `  esac

  case "$path" in
`)
	distroPaths := pathsTakingKind(argDistro)
	if len(distroPaths) > 0 {
		fmt.Fprintf(w, "    %s)\n      offered=\"$offered $(_wslkit_distros)\" ;;\n", strings.Join(quoteAllBashCase(distroPaths), "|"))
	}
	fmt.Fprint(w, `  esac

  COMPREPLY=( $(compgen -W "$offered" -- "$cur") )
}

complete -F _wslkit wslkit
`)
}

func writeZshCompletion(w io.Writer) {
	fmt.Fprint(w, `#compdef wslkit
# wslkit completion for zsh.
# Generated by: wslkit completion zsh
# Install with: source <(wslkit completion zsh)

_wslkit_distros() {
  local -a names
  # Asked at completion time, so a distribution installed since this script was
  # generated still completes.
  names=( ${(f)"$(wslkit disk list --json 2>/dev/null | sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"} )
  _describe 'distribution' names
}

_wslkit() {
  local path="" candidate word
  local -a offered
  for word in ${words[2,$((CURRENT-1))]}; do
    [[ $word == -* ]] && continue
    if [[ -z $path ]]; then candidate=$word; else candidate="$path $word"; fi
    case "$candidate" in
`)
	for _, e := range completionEntries() {
		fmt.Fprintf(w, "      %s) path=%q ;;\n", quoteBashCase(e.Path), e.Path)
	}
	fmt.Fprint(w, `      *) break ;;
    esac
  done

  case "$path" in
`)
	for _, e := range completionEntries() {
		fmt.Fprintf(w, "    %s) offered=( ${=%q} ) ;;\n", quoteBashCase(e.Path), e.words())
	}
	fmt.Fprintf(w, "    *) offered=( ${=%q} ) ;;\n", strings.Join(topLevelNames(), " ")+" "+strings.Join(globalFlags, " "))
	fmt.Fprint(w, `  esac

  case "$path" in
`)
	distroPaths := pathsTakingKind(argDistro)
	if len(distroPaths) > 0 {
		fmt.Fprintf(w, "    %s) _wslkit_distros ;;\n", strings.Join(quoteAllBashCase(distroPaths), "|"))
	}
	fmt.Fprint(w, `  esac

  compadd -a offered
}

compdef _wslkit wslkit
`)
}

// topLevelNames lists the commands offered with nothing typed yet.
func topLevelNames() []string {
	var out []string
	for _, n := range CommandTree() {
		out = append(out, n.Name)
	}
	return out
}

// pathsTakingKind lists the command paths whose first positional accepts a
// given kind.
func pathsTakingKind(kind argKind) []string {
	var out []string
	for _, e := range completionEntries() {
		if e.firstArg() == kind {
			out = append(out, e.Path)
		}
	}
	return out
}

// quoteBashCase renders a command path as a case pattern. The paths are made of
// letters, digits, hyphens and spaces, so quoting is all that is needed.
func quoteBashCase(path string) string {
	return `"` + path + `"`
}

func quoteAllBashCase(paths []string) []string {
	out := make([]string, 0, len(paths))
	for _, p := range paths {
		out = append(out, quoteBashCase(p))
	}
	return out
}

// completion prints a shell completion script.
//
// It runs before anything is constructed: no registry, no filesystem, no WSL,
// so it works on a machine where WSL is not installed at all.
func (a *App) completion(args []string) int {
	if len(args) != 1 || strings.HasPrefix(args[0], "-") {
		fmt.Fprintf(a.Stderr, "usage: wslkit completion <%s>\n", strings.Join(Shells, "|"))
		return ExitUsage
	}
	if err := WriteCompletion(a.Stdout, args[0]); err != nil {
		fmt.Fprintf(a.Stderr, "error: %v\n", err)
		return ExitUsage
	}
	return ExitOK
}
