// Command gen-winget rewrites the winget manifests for a published release.
//
// The hashes come from the release's own checksums.txt, not from a download
// this recomputes: the publisher already said what it built, and a second
// opinion derived from a possibly-truncated download is worth less than the
// first one.
//
//	go run ./tools/gen-winget -version 0.1.0          rewrite them
//	go run ./tools/gen-winget -version 0.1.0 -check   fail if they are stale
//
// The check mode is what the release workflow runs, so a tag whose manifests
// were never regenerated fails the build rather than shipping a version nobody
// can install.
package main

import (
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	repo    = "wslkit/wslkit"
	pkgID   = "wslkit.wslkit"
	dirName = "packaging/winget"
)

func main() {
	version := flag.String("version", "", "release version, without the leading v")
	check := flag.Bool("check", false, "fail if the manifests are not what this would write")
	dir := flag.String("dir", dirName, "where the manifests live")
	date := flag.String("date", "", "release date (default: today)")
	flag.Parse()

	if *version == "" {
		fmt.Fprintln(os.Stderr, "gen-winget: -version is required, for example -version 0.1.0")
		os.Exit(2)
	}
	v := strings.TrimPrefix(*version, "v")
	if *date == "" {
		*date = time.Now().UTC().Format("2006-01-02")
	}

	sums, err := checksums(v)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-winget: %v\n", err)
		os.Exit(1)
	}
	amd64Hash, ok := sums[fmt.Sprintf("wslkit_%s_windows_amd64.zip", v)]
	if !ok {
		fmt.Fprintf(os.Stderr, "gen-winget: no amd64 archive in the checksums for %s\n", v)
		os.Exit(1)
	}
	arm64Hash, ok := sums[fmt.Sprintf("wslkit_%s_windows_arm64.zip", v)]
	if !ok {
		fmt.Fprintf(os.Stderr, "gen-winget: no arm64 archive in the checksums for %s\n", v)
		os.Exit(1)
	}

	files := map[string]string{
		pkgID + ".installer.yaml":    installer(v, *date, amd64Hash, arm64Hash),
		pkgID + ".locale.en-US.yaml": locale(v),
		pkgID + ".yaml":              versionManifest(v),
	}

	stale := false
	for name, want := range files {
		path := filepath.Join(*dir, name)
		if *check {
			got, err := os.ReadFile(path)
			if err != nil || string(got) != want {
				fmt.Fprintf(os.Stderr, "gen-winget: %s is out of date; run go run ./tools/gen-winget -version %s\n", path, v)
				stale = true
			}
			continue
		}
		if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "gen-winget: %v\n", err)
			os.Exit(1)
		}
		fmt.Println("wrote", path)
	}
	if stale {
		os.Exit(1)
	}
}

// checksums reads the release's own checksums.txt.
func checksums(version string) (map[string]string, error) {
	url := fmt.Sprintf("https://github.com/%s/releases/download/v%s/checksums.txt", repo, version)
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("fetching %s: %w", url, err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("fetching %s: %s", url, resp.Status)
	}
	b, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, line := range strings.Split(string(b), "\n") {
		fields := strings.Fields(strings.TrimSpace(line))
		if len(fields) == 2 {
			out[fields[1]] = strings.ToUpper(fields[0])
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s held no checksums", url)
	}
	return out, nil
}

func installer(v, date, amd64Hash, arm64Hash string) string {
	base := fmt.Sprintf("https://github.com/%s/releases/download/v%s", repo, v)
	return fmt.Sprintf(`# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
# Generated by tools/gen-winget. Do not edit; run the generator.
PackageIdentifier: %s
PackageVersion: %s
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: wslkit.exe
    PortableCommandAlias: wslkit
  # The same binary under its older name. Invoked as wsldoctor it runs
  # `+"`wslkit doctor`"+`, so anything written against wsldoctor keeps working.
  - RelativeFilePath: wslkit.exe
    PortableCommandAlias: wsldoctor
UpgradeBehavior: install
ReleaseDate: %s
Installers:
  - Architecture: x64
    InstallerUrl: %s/wslkit_%s_windows_amd64.zip
    InstallerSha256: %s
  - Architecture: arm64
    InstallerUrl: %s/wslkit_%s_windows_arm64.zip
    InstallerSha256: %s
ManifestType: installer
ManifestVersion: 1.6.0
`, pkgID, v, date, base, v, amd64Hash, base, v, arm64Hash)
}

func locale(v string) string {
	return fmt.Sprintf(`# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json
# Generated by tools/gen-winget. Do not edit; run the generator.
PackageIdentifier: %s
PackageVersion: %s
PackageLocale: en-US
Publisher: wslkit
PublisherUrl: https://github.com/wslkit
PublisherSupportUrl: https://github.com/%s/issues
PackageName: wslkit
PackageUrl: https://github.com/%s
License: MIT
LicenseUrl: https://github.com/%s/blob/main/LICENSE
ShortDescription: Tools for WSL 2 - diagnose why it is broken or slow, then fix it.
Description: |-
  wslkit diagnoses why WSL 2 is broken or slow and then fixes it. Everything that
  only reads runs without administrator rights, nothing leaves the machine unless
  asked, and every change prints its plan first and records how to undo itself.

  doctor gives a ranked diagnosis with remediations. disk lists, trims, compacts,
  moves, rebuilds and trashes the virtual disks behind WSL 2, including the ones
  no distribution claims. proxy gets a Windows proxy, PAC script included, working
  inside a distribution. top shows what the utility VM is using and which
  distribution is responsible. agent and sock bridge ssh-agent and gpg-agent from
  Windows into a distribution.
Moniker: wslkit
Tags:
  - wsl
  - wsl2
  - diagnostics
  - troubleshooting
  - windows-subsystem-for-linux
ReleaseNotesUrl: https://github.com/%s/releases/tag/v%s
Documentation:
  - DocumentLabel: Documentation
    DocumentUrl: https://wslkit.github.io/wslkit/
ManifestType: defaultLocale
ManifestVersion: 1.6.0
`, pkgID, v, repo, repo, repo, repo, v)
}

func versionManifest(v string) string {
	return fmt.Sprintf(`# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
# Generated by tools/gen-winget. Do not edit; run the generator.
PackageIdentifier: %s
PackageVersion: %s
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
`, pkgID, v)
}
